---
- name: Installing postgresql server
  hosts: all
  become: yes
  vars:
   src_path: /postgres
   dst_path: /postgres
   psqlconf: /var/lib/pgsql/14/data/
   sharbuff: "{{ (ansible_memtotal_mb/4) | round | int }}"
   wrkmem: "{{ (ansible_memtotal_mb/32) | round | int }}"
   mainwrkmem: "{{ (ansible_memtotal_mb/16) | round | int }}"
   pg: postgresql-14
  tasks:
   - name: make dir postgres
     file:
      path: /postgres/
      state: directory
      mode: '0777'
   - name: make dir addon
     file:
      path: /postgres/addon
      state: directory
      mode: '0777'

   - name: make dir for pgstatstmp
     file:
      path: /var/lib/pgsql_stats_tmp
      state: directory
      mode: '0777'


   - name: change fstab for tmp table
     lineinfile:
         path: /etc/apt/sources.list
         regexp: 'deb http://archive.ubuntu.com/ubuntu bionic multiverse'
         line: 'deb http://archive.ubuntu.com/ubuntu bionic multiverse'


#   - name: change fstab for tmp table
#     lineinfile:
#         path: /etc/fstab
#         regexp: 'tmpfs /var/lib/pgsql_stats_tmp tmpfs size=1G,uid=postgres,gid=postgres 0 0'
#         line: 'tmpfs /var/lib/pgsql_stats_tmp tmpfs size=1G,uid=postgres,gid=postgres 0 0'

#   - name: change fstab for pg DATA
#     lineinfile:
#         path: /etc/fstab
#         regexp: '/dev/sda4 {{ psqlconf }} tmpfs auto,uid=pgdata,gid=pgdata 0 0'
#         line: '/dev/sda4 {{ psqlconf }} tmpfs auto,uid=pgdata,gid=pgdata 0 0'

#   - name: change fstab for tmp table
#     lineinfile:
#         path: /etc/fstab
#         regexp: '//192.168.1.10/POSTGRES /mnt/share/ cifs auto,user,iocharset=utf8,uid=111,username=forsaga,password=39533953 0 0'
#        line: '//192.168.1.10/POSTGRES /mnt/share/ cifs auto,user,iocharset=utf8,uid=111,username=forsaga,password=39533953 0 0'
   
   
   - block:

        - name: installing some apps
          apt:
           name:
            - cifs-utils
            - mc
           state: latest

        - name: mount share
          mount:
           src: //192.168.1.10/POSTGRES
           path: /mnt/share/
           fstype: cifs
           opts: 'username=forsaga,password=39533953'
           state: mounted

        - name: mount pgtmp
          mount:
           path: /var/lib/pgsql_stats_tmp
           fstype: tmpfs
           state: mounted


         - name: downloan ru postgrespro repo
           get_url:
            url: https://repo.postgrespro.ru/pg1c-14/keys/pgpro-repo-add.sh
            dest: /postgres/
            mode: '0440'
#        - name: Copy deb packages from ansible server
#          copy:
#           src: '{{ item }}'
#           dest: '{{ dst_path }}'
#          with_fileglob:
#           - '{{ src_path }}/*.deb'

#        - name: installing postgresql server
#          apt:
#           name:
#            - '{{ dst_path }}/libpq5_14.2-3.1C_amd64.deb'
#            - '{{ dst_path }}/postgresql-14_14.2-3.1C_amd64.deb'
#            - '{{ dst_path }}/postgresql-client-14_14.2-3.1C_amd64.deb'
            
#        - name: Copy addon deb packages from ansible server
#          copy:
#           src: '{{ item }}'
#           dest: '{{ dst_path }}/addon/'
#          with_fileglob:
#           - '{{ src_path }}/addon/*.deb'

#        - name: installing postgresql addon
#          apt:
#           name:
#            - '{{ item }}'
#          with_fileglob:
#            - '{{ dst_path }}/addon/*.deb'

     

        - name: "Check initializing pg database"
          stat:
            path: /var/lib/pgsql/14/data/
          register: pgdata

        - name: initialize pg database
          command: /usr/pgsql-14/bin/postgresql-14-setup initdb
          when: pgdata.stat.isreg is undefined

        - name: start and enable pgsql service
          service:
           name: '{{ pg }}'
           state: started
           enabled: yes


     when: ansible_distribution == "Ubuntu"

   - name: pd reset database user
     become_user: postgres
     postgresql_user:
      name: "postgres"
      password: "postgres"

   - name: change postgres network 
     lineinfile:
         path: '{{ psqlconf }}/postgresql.conf'
         regexp: '^listen_addresses'
         line: "listen_addresses = '*'"

   - name: change postgres pg hba access
     lineinfile:
         path: '{{ psqlconf }}/pg_hba.conf'
         regexp: 'host   all   all  0.0.0.0/0  md5'
         line: 'host   all   all  0.0.0.0/0  md5'

   - name: set temp buffer for psql.conf
     lineinfile:
         path: '{{ psqlconf }}/postgresql.conf'
         regexp: '^temp_buffers'
         insertafter: '#temp_buffers'
         line: 'temp_buffers = 256MB'
         state: present

   - name: set shared buffer for psql.conf
     lineinfile:
         path: '{{ psqlconf }}/postgresql.conf'
         regexp: '^shared_buffers'
         insertafter: 'shared_buffers'
         line: "shared_buffers = {{ sharbuff }}MB"
         state: present

   - name: set work mem for psql.conf
     lineinfile:
         path: '{{ psqlconf }}/postgresql.conf'
         regexp: '^work_mem'
         insertafter: 'work_mem'
         line: "work_mem = {{ wrkmem }}MB"
         state: present

   - name: set maintanance_work_mem for psql.conf
     lineinfile:
         path: '{{ psqlconf }}/postgresql.conf'
         regexp: '^maintenance_work_mem'
         insertafter: 'maintenance_work_mem'
         line: "maintenance_work_mem = {{ mainwrkmem }}MB"
         state: present